### ISSUE TITLE
Config file typo

### ISSUE THREAD

**Issue by abrookewood** [jamesontriplett/mule_linux_service_install#1]
Hi, thanks for this - very helpful! I think the MULE_HOME value is incorrect in your Init.d parameter file:
From: MULE_HOME=/usr/local/mule-dev
To: MULE_HOME=/usr/local/mule/mule-dev

**Comment by jamesonwildwood** [comment]
This is more a matter of opinion than a typo.  You can create them in /usr/local/mule, or /usr/local

**Comment by abrookewood** [comment]
OK - I just thought it would need to be consistent since you use /usr/local/mule/mule-dev throughout the rest of the documentation. Anyway, thanks for the script!
